### ISSUE TITLE
Missing sql

### ISSUE THREAD

**Issue by NexDK** [raiderss/es-garage#1]
Hi, it seems like the sql file is missing.

```
[      script:oxmysql] Error: es-garage was unable to execute a query!
[      script:oxmysql] Query: UPDATE player_vehicles SET state = 1 WHERE state = 0
[      script:oxmysql] []
[      script:oxmysql] Table 'dev.player_vehicles' doesn't exist
```

**Comment by raiderss** [comment]
search for player_vehicles in server.lua, make it dev.player.vehicles or choose the framework correctly because it is probably looking for the wrong place, try ESX to search for owned_vehicles
